# Generated by Django 2.2.16 on 2020-10-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_auto_20201024_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesapp',
            name='title',
            field=models.CharField(default='Technology', max_length=100),
        ),
    ]
