# Generated by Django 2.2.16 on 2020-10-25 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_notesapp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesapp',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
